<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence+, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter+)>
<!ATTLIST alphabet id (amino-acid|nucleotide) #REQUIRED
                   length CDATA #REQUIRED>
<!ELEMENT ambigs (letter+)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif+)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site+)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref+)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites+)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value+)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array+)>

]>
<!-- Begin document body -->
<MEME version="4.6.0" release="Thu Jan 20 14:06:48 PST 2011">
<training_set datafile="dataset_3.dat" length="30">
<alphabet id="amino-acid" length="20">
<letter id="letter_A" symbol="A"/>
<letter id="letter_C" symbol="C"/>
<letter id="letter_D" symbol="D"/>
<letter id="letter_E" symbol="E"/>
<letter id="letter_F" symbol="F"/>
<letter id="letter_G" symbol="G"/>
<letter id="letter_H" symbol="H"/>
<letter id="letter_I" symbol="I"/>
<letter id="letter_K" symbol="K"/>
<letter id="letter_L" symbol="L"/>
<letter id="letter_M" symbol="M"/>
<letter id="letter_N" symbol="N"/>
<letter id="letter_P" symbol="P"/>
<letter id="letter_Q" symbol="Q"/>
<letter id="letter_R" symbol="R"/>
<letter id="letter_S" symbol="S"/>
<letter id="letter_T" symbol="T"/>
<letter id="letter_V" symbol="V"/>
<letter id="letter_W" symbol="W"/>
<letter id="letter_Y" symbol="Y"/>
</alphabet>
<ambigs>
<letter id="letter_B" symbol="B"/>
<letter id="letter_J" symbol="J"/>
<letter id="letter_O" symbol="O"/>
<letter id="letter_U" symbol="U"/>
<letter id="letter_X" symbol="X"/>
<letter id="letter_Z" symbol="Z"/>
<letter id="letter_star" symbol="*"/>
<letter id="letter_-" symbol="-"/>
</ambigs>
<sequence id="sequence_0" name="chr21_19617074_19617124_+" length="50" weight="1.000000" />
<sequence id="sequence_1" name="chr21_26934381_26934431_+" length="50" weight="1.000000" />
<sequence id="sequence_2" name="chr21_28217753_28217803_-" length="50" weight="1.000000" />
<sequence id="sequence_3" name="chr21_31710037_31710087_-" length="50" weight="1.000000" />
<sequence id="sequence_4" name="chr21_31744582_31744632_-" length="50" weight="1.000000" />
<sequence id="sequence_5" name="chr21_31768316_31768366_+" length="50" weight="1.000000" />
<sequence id="sequence_6" name="chr21_31914206_31914256_-" length="50" weight="1.000000" />
<sequence id="sequence_7" name="chr21_31933633_31933683_-" length="50" weight="1.000000" />
<sequence id="sequence_8" name="chr21_31962741_31962791_-" length="50" weight="1.000000" />
<sequence id="sequence_9" name="chr21_31964683_31964733_+" length="50" weight="1.000000" />
<sequence id="sequence_10" name="chr21_31973364_31973414_+" length="50" weight="1.000000" />
<sequence id="sequence_11" name="chr21_31992870_31992920_+" length="50" weight="1.000000" />
<sequence id="sequence_12" name="chr21_32185595_32185645_-" length="50" weight="1.000000" />
<sequence id="sequence_13" name="chr21_32202076_32202126_-" length="50" weight="1.000000" />
<sequence id="sequence_14" name="chr21_32253899_32253949_-" length="50" weight="1.000000" />
<sequence id="sequence_15" name="chr21_32410820_32410870_-" length="50" weight="1.000000" />
<sequence id="sequence_16" name="chr21_36411748_36411798_-" length="50" weight="1.000000" />
<sequence id="sequence_17" name="chr21_37838750_37838800_-" length="50" weight="1.000000" />
<sequence id="sequence_18" name="chr21_45705687_45705737_+" length="50" weight="1.000000" />
<sequence id="sequence_19" name="chr21_45971413_45971463_-" length="50" weight="1.000000" />
<sequence id="sequence_20" name="chr21_45978668_45978718_-" length="50" weight="1.000000" />
<sequence id="sequence_21" name="chr21_45993530_45993580_+" length="50" weight="1.000000" />
<sequence id="sequence_22" name="chr21_46020421_46020471_+" length="50" weight="1.000000" />
<sequence id="sequence_23" name="chr21_46031920_46031970_+" length="50" weight="1.000000" />
<sequence id="sequence_24" name="chr21_46046964_46047014_+" length="50" weight="1.000000" />
<sequence id="sequence_25" name="chr21_46057197_46057247_+" length="50" weight="1.000000" />
<sequence id="sequence_26" name="chr21_46086869_46086919_-" length="50" weight="1.000000" />
<sequence id="sequence_27" name="chr21_46102103_46102153_-" length="50" weight="1.000000" />
<sequence id="sequence_28" name="chr21_47517957_47518007_+" length="50" weight="1.000000" />
<sequence id="sequence_29" name="chr21_47575506_47575556_-" length="50" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="letter_A">0.294</value>
<value letter_id="letter_C">0.231</value>
<value letter_id="letter_D">0.000</value>
<value letter_id="letter_E">0.000</value>
<value letter_id="letter_F">0.000</value>
<value letter_id="letter_G">0.257</value>
<value letter_id="letter_H">0.000</value>
<value letter_id="letter_I">0.000</value>
<value letter_id="letter_K">0.000</value>
<value letter_id="letter_L">0.000</value>
<value letter_id="letter_M">0.000</value>
<value letter_id="letter_N">0.000</value>
<value letter_id="letter_P">0.000</value>
<value letter_id="letter_Q">0.000</value>
<value letter_id="letter_R">0.000</value>
<value letter_id="letter_S">0.000</value>
<value letter_id="letter_T">0.217</value>
<value letter_id="letter_V">0.000</value>
<value letter_id="letter_W">0.000</value>
<value letter_id="letter_Y">0.000</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme dataset_3.dat -o dataset_4_files -nostatus </command_line>
<host>scofield</host>
<type>zoops</type>
<nmotifs>1</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<min_width>8</min_width>
<max_width>50</max_width>
<minic>    0.00</minic>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<minsites>2</minsites>
<maxsites>30</maxsites>
<wnsites>0.8</wnsites>
<prob>1</prob>
<spmap>pam</spmap>
<spfuzz>120</spfuzz>
<prior>megap</prior>
<beta>7500</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>30</num_sequences>
<num_positions>1500</num_positions>
<seed>0</seed>
<seqfrac>       1</seqfrac>
<strands>none</strands>
<priors_file>prior30.plib</priors_file>
<reason_for_stopping>Stopped because nmotifs = 1 reached.</reason_for_stopping>
<background_frequencies source="dataset with add-one prior applied">
<alphabet_array>
<value letter_id="letter_A">0.291</value>
<value letter_id="letter_C">0.229</value>
<value letter_id="letter_D">0.001</value>
<value letter_id="letter_E">0.001</value>
<value letter_id="letter_F">0.001</value>
<value letter_id="letter_G">0.255</value>
<value letter_id="letter_H">0.001</value>
<value letter_id="letter_I">0.001</value>
<value letter_id="letter_K">0.001</value>
<value letter_id="letter_L">0.001</value>
<value letter_id="letter_M">0.001</value>
<value letter_id="letter_N">0.001</value>
<value letter_id="letter_P">0.001</value>
<value letter_id="letter_Q">0.001</value>
<value letter_id="letter_R">0.001</value>
<value letter_id="letter_S">0.001</value>
<value letter_id="letter_T">0.215</value>
<value letter_id="letter_V">0.001</value>
<value letter_id="letter_W">0.001</value>
<value letter_id="letter_Y">0.001</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="1" width="11" sites="25" ic="40.0" re="13.8" llr="239" e_value="2.4e-011" bayes_threshold="5.33554" elapsed_time="2.128133">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="letter_A">-32</value>
<value letter_id="letter_C">-680</value>
<value letter_id="letter_D">91</value>
<value letter_id="letter_E">77</value>
<value letter_id="letter_F">7</value>
<value letter_id="letter_G">138</value>
<value letter_id="letter_H">-20</value>
<value letter_id="letter_I">55</value>
<value letter_id="letter_K">64</value>
<value letter_id="letter_L">107</value>
<value letter_id="letter_M">11</value>
<value letter_id="letter_N">150</value>
<value letter_id="letter_P">142</value>
<value letter_id="letter_Q">72</value>
<value letter_id="letter_R">87</value>
<value letter_id="letter_S">396</value>
<value letter_id="letter_T">-148</value>
<value letter_id="letter_V">221</value>
<value letter_id="letter_W">-140</value>
<value letter_id="letter_Y">-36</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-11</value>
<value letter_id="letter_C">-680</value>
<value letter_id="letter_D">89</value>
<value letter_id="letter_E">76</value>
<value letter_id="letter_F">7</value>
<value letter_id="letter_G">137</value>
<value letter_id="letter_H">-21</value>
<value letter_id="letter_I">55</value>
<value letter_id="letter_K">63</value>
<value letter_id="letter_L">107</value>
<value letter_id="letter_M">10</value>
<value letter_id="letter_N">149</value>
<value letter_id="letter_P">141</value>
<value letter_id="letter_Q">71</value>
<value letter_id="letter_R">87</value>
<value letter_id="letter_S">396</value>
<value letter_id="letter_T">-239</value>
<value letter_id="letter_V">220</value>
<value letter_id="letter_W">-140</value>
<value letter_id="letter_Y">-36</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-79</value>
<value letter_id="letter_C">41</value>
<value letter_id="letter_D">4</value>
<value letter_id="letter_E">21</value>
<value letter_id="letter_F">-7</value>
<value letter_id="letter_G">44</value>
<value letter_id="letter_H">-62</value>
<value letter_id="letter_I">42</value>
<value letter_id="letter_K">-5</value>
<value letter_id="letter_L">99</value>
<value letter_id="letter_M">0</value>
<value letter_id="letter_N">99</value>
<value letter_id="letter_P">138</value>
<value letter_id="letter_Q">52</value>
<value letter_id="letter_R">42</value>
<value letter_id="letter_S">399</value>
<value letter_id="letter_T">-46</value>
<value letter_id="letter_V">223</value>
<value letter_id="letter_W">-173</value>
<value letter_id="letter_Y">-68</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">11</value>
<value letter_id="letter_C">-677</value>
<value letter_id="letter_D">48</value>
<value letter_id="letter_E">47</value>
<value letter_id="letter_F">-2</value>
<value letter_id="letter_G">127</value>
<value letter_id="letter_H">-43</value>
<value letter_id="letter_I">46</value>
<value letter_id="letter_K">27</value>
<value letter_id="letter_L">101</value>
<value letter_id="letter_M">3</value>
<value letter_id="letter_N">124</value>
<value letter_id="letter_P">138</value>
<value letter_id="letter_Q">60</value>
<value letter_id="letter_R">62</value>
<value letter_id="letter_S">397</value>
<value letter_id="letter_T">-235</value>
<value letter_id="letter_V">220</value>
<value letter_id="letter_W">-160</value>
<value letter_id="letter_Y">-55</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-596</value>
<value letter_id="letter_C">-820</value>
<value letter_id="letter_D">12</value>
<value letter_id="letter_E">-21</value>
<value letter_id="letter_F">-53</value>
<value letter_id="letter_G">-267</value>
<value letter_id="letter_H">-74</value>
<value letter_id="letter_I">37</value>
<value letter_id="letter_K">16</value>
<value letter_id="letter_L">44</value>
<value letter_id="letter_M">-37</value>
<value letter_id="letter_N">98</value>
<value letter_id="letter_P">31</value>
<value letter_id="letter_Q">9</value>
<value letter_id="letter_R">19</value>
<value letter_id="letter_S">319</value>
<value letter_id="letter_T">212</value>
<value letter_id="letter_V">127</value>
<value letter_id="letter_W">-193</value>
<value letter_id="letter_Y">-95</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">165</value>
<value letter_id="letter_C">-261</value>
<value letter_id="letter_D">70</value>
<value letter_id="letter_E">110</value>
<value letter_id="letter_F">77</value>
<value letter_id="letter_G">-521</value>
<value letter_id="letter_H">-4</value>
<value letter_id="letter_I">147</value>
<value letter_id="letter_K">95</value>
<value letter_id="letter_L">201</value>
<value letter_id="letter_M">90</value>
<value letter_id="letter_N">121</value>
<value letter_id="letter_P">124</value>
<value letter_id="letter_Q">91</value>
<value letter_id="letter_R">107</value>
<value letter_id="letter_S">425</value>
<value letter_id="letter_T">-527</value>
<value letter_id="letter_V">314</value>
<value letter_id="letter_W">-95</value>
<value letter_id="letter_Y">8</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-838</value>
<value letter_id="letter_C">-990</value>
<value letter_id="letter_D">-89</value>
<value letter_id="letter_E">-149</value>
<value letter_id="letter_F">-151</value>
<value letter_id="letter_G">-841</value>
<value letter_id="letter_H">-161</value>
<value letter_id="letter_I">-117</value>
<value letter_id="letter_K">-113</value>
<value letter_id="letter_L">-66</value>
<value letter_id="letter_M">-209</value>
<value letter_id="letter_N">-68</value>
<value letter_id="letter_P">-69</value>
<value letter_id="letter_Q">-129</value>
<value letter_id="letter_R">-91</value>
<value letter_id="letter_S">111</value>
<value letter_id="letter_T">221</value>
<value letter_id="letter_V">-55</value>
<value letter_id="letter_W">-255</value>
<value letter_id="letter_Y">-173</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">176</value>
<value letter_id="letter_C">-858</value>
<value letter_id="letter_D">-79</value>
<value letter_id="letter_E">-103</value>
<value letter_id="letter_F">-115</value>
<value letter_id="letter_G">-717</value>
<value letter_id="letter_H">-148</value>
<value letter_id="letter_I">-95</value>
<value letter_id="letter_K">-108</value>
<value letter_id="letter_L">-17</value>
<value letter_id="letter_M">-162</value>
<value letter_id="letter_N">-61</value>
<value letter_id="letter_P">-12</value>
<value letter_id="letter_Q">-95</value>
<value letter_id="letter_R">-69</value>
<value letter_id="letter_S">193</value>
<value letter_id="letter_T">-737</value>
<value letter_id="letter_V">52</value>
<value letter_id="letter_W">-240</value>
<value letter_id="letter_Y">-153</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">134</value>
<value letter_id="letter_C">-686</value>
<value letter_id="letter_D">0</value>
<value letter_id="letter_E">16</value>
<value letter_id="letter_F">-12</value>
<value letter_id="letter_G">-553</value>
<value letter_id="letter_H">-68</value>
<value letter_id="letter_I">44</value>
<value letter_id="letter_K">-8</value>
<value letter_id="letter_L">96</value>
<value letter_id="letter_M">-9</value>
<value letter_id="letter_N">88</value>
<value letter_id="letter_P">124</value>
<value letter_id="letter_Q">41</value>
<value letter_id="letter_R">36</value>
<value letter_id="letter_S">384</value>
<value letter_id="letter_T">11</value>
<value letter_id="letter_V">216</value>
<value letter_id="letter_W">-177</value>
<value letter_id="letter_Y">-71</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">165</value>
<value letter_id="letter_C">-261</value>
<value letter_id="letter_D">70</value>
<value letter_id="letter_E">110</value>
<value letter_id="letter_F">77</value>
<value letter_id="letter_G">-521</value>
<value letter_id="letter_H">-4</value>
<value letter_id="letter_I">147</value>
<value letter_id="letter_K">95</value>
<value letter_id="letter_L">201</value>
<value letter_id="letter_M">90</value>
<value letter_id="letter_N">121</value>
<value letter_id="letter_P">124</value>
<value letter_id="letter_Q">91</value>
<value letter_id="letter_R">107</value>
<value letter_id="letter_S">425</value>
<value letter_id="letter_T">-527</value>
<value letter_id="letter_V">314</value>
<value letter_id="letter_W">-95</value>
<value letter_id="letter_Y">8</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">147</value>
<value letter_id="letter_C">-614</value>
<value letter_id="letter_D">89</value>
<value letter_id="letter_E">129</value>
<value letter_id="letter_F">93</value>
<value letter_id="letter_G">-121</value>
<value letter_id="letter_H">12</value>
<value letter_id="letter_I">160</value>
<value letter_id="letter_K">113</value>
<value letter_id="letter_L">217</value>
<value letter_id="letter_M">108</value>
<value letter_id="letter_N">144</value>
<value letter_id="letter_P">144</value>
<value letter_id="letter_Q">111</value>
<value letter_id="letter_R">125</value>
<value letter_id="letter_S">447</value>
<value letter_id="letter_T">-241</value>
<value letter_id="letter_V">332</value>
<value letter_id="letter_W">-81</value>
<value letter_id="letter_Y">22</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="letter_A">0.240000</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_D">0.000000</value>
<value letter_id="letter_E">0.000000</value>
<value letter_id="letter_F">0.000000</value>
<value letter_id="letter_G">0.680000</value>
<value letter_id="letter_H">0.000000</value>
<value letter_id="letter_I">0.000000</value>
<value letter_id="letter_K">0.000000</value>
<value letter_id="letter_L">0.000000</value>
<value letter_id="letter_M">0.000000</value>
<value letter_id="letter_N">0.000000</value>
<value letter_id="letter_P">0.000000</value>
<value letter_id="letter_Q">0.000000</value>
<value letter_id="letter_R">0.000000</value>
<value letter_id="letter_S">0.000000</value>
<value letter_id="letter_T">0.080000</value>
<value letter_id="letter_V">0.000000</value>
<value letter_id="letter_W">0.000000</value>
<value letter_id="letter_Y">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.280000</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_D">0.000000</value>
<value letter_id="letter_E">0.000000</value>
<value letter_id="letter_F">0.000000</value>
<value letter_id="letter_G">0.680000</value>
<value letter_id="letter_H">0.000000</value>
<value letter_id="letter_I">0.000000</value>
<value letter_id="letter_K">0.000000</value>
<value letter_id="letter_L">0.000000</value>
<value letter_id="letter_M">0.000000</value>
<value letter_id="letter_N">0.000000</value>
<value letter_id="letter_P">0.000000</value>
<value letter_id="letter_Q">0.000000</value>
<value letter_id="letter_R">0.000000</value>
<value letter_id="letter_S">0.000000</value>
<value letter_id="letter_T">0.040000</value>
<value letter_id="letter_V">0.000000</value>
<value letter_id="letter_W">0.000000</value>
<value letter_id="letter_Y">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.160000</value>
<value letter_id="letter_C">0.320000</value>
<value letter_id="letter_D">0.000000</value>
<value letter_id="letter_E">0.000000</value>
<value letter_id="letter_F">0.000000</value>
<value letter_id="letter_G">0.360000</value>
<value letter_id="letter_H">0.000000</value>
<value letter_id="letter_I">0.000000</value>
<value letter_id="letter_K">0.000000</value>
<value letter_id="letter_L">0.000000</value>
<value letter_id="letter_M">0.000000</value>
<value letter_id="letter_N">0.000000</value>
<value letter_id="letter_P">0.000000</value>
<value letter_id="letter_Q">0.000000</value>
<value letter_id="letter_R">0.000000</value>
<value letter_id="letter_S">0.000000</value>
<value letter_id="letter_T">0.160000</value>
<value letter_id="letter_V">0.000000</value>
<value letter_id="letter_W">0.000000</value>
<value letter_id="letter_Y">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.320000</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_D">0.000000</value>
<value letter_id="letter_E">0.000000</value>
<value letter_id="letter_F">0.000000</value>
<value letter_id="letter_G">0.640000</value>
<value letter_id="letter_H">0.000000</value>
<value letter_id="letter_I">0.000000</value>
<value letter_id="letter_K">0.000000</value>
<value letter_id="letter_L">0.000000</value>
<value letter_id="letter_M">0.000000</value>
<value letter_id="letter_N">0.000000</value>
<value letter_id="letter_P">0.000000</value>
<value letter_id="letter_Q">0.000000</value>
<value letter_id="letter_R">0.000000</value>
<value letter_id="letter_S">0.000000</value>
<value letter_id="letter_T">0.040000</value>
<value letter_id="letter_V">0.000000</value>
<value letter_id="letter_W">0.000000</value>
<value letter_id="letter_Y">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_D">0.000000</value>
<value letter_id="letter_E">0.000000</value>
<value letter_id="letter_F">0.000000</value>
<value letter_id="letter_G">0.040000</value>
<value letter_id="letter_H">0.000000</value>
<value letter_id="letter_I">0.000000</value>
<value letter_id="letter_K">0.000000</value>
<value letter_id="letter_L">0.000000</value>
<value letter_id="letter_M">0.000000</value>
<value letter_id="letter_N">0.000000</value>
<value letter_id="letter_P">0.000000</value>
<value letter_id="letter_Q">0.000000</value>
<value letter_id="letter_R">0.000000</value>
<value letter_id="letter_S">0.000000</value>
<value letter_id="letter_T">0.960000</value>
<value letter_id="letter_V">0.000000</value>
<value letter_id="letter_W">0.000000</value>
<value letter_id="letter_Y">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.960000</value>
<value letter_id="letter_C">0.040000</value>
<value letter_id="letter_D">0.000000</value>
<value letter_id="letter_E">0.000000</value>
<value letter_id="letter_F">0.000000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_H">0.000000</value>
<value letter_id="letter_I">0.000000</value>
<value letter_id="letter_K">0.000000</value>
<value letter_id="letter_L">0.000000</value>
<value letter_id="letter_M">0.000000</value>
<value letter_id="letter_N">0.000000</value>
<value letter_id="letter_P">0.000000</value>
<value letter_id="letter_Q">0.000000</value>
<value letter_id="letter_R">0.000000</value>
<value letter_id="letter_S">0.000000</value>
<value letter_id="letter_T">0.000000</value>
<value letter_id="letter_V">0.000000</value>
<value letter_id="letter_W">0.000000</value>
<value letter_id="letter_Y">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_D">0.000000</value>
<value letter_id="letter_E">0.000000</value>
<value letter_id="letter_F">0.000000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_H">0.000000</value>
<value letter_id="letter_I">0.000000</value>
<value letter_id="letter_K">0.000000</value>
<value letter_id="letter_L">0.000000</value>
<value letter_id="letter_M">0.000000</value>
<value letter_id="letter_N">0.000000</value>
<value letter_id="letter_P">0.000000</value>
<value letter_id="letter_Q">0.000000</value>
<value letter_id="letter_R">0.000000</value>
<value letter_id="letter_S">0.000000</value>
<value letter_id="letter_T">1.000000</value>
<value letter_id="letter_V">0.000000</value>
<value letter_id="letter_W">0.000000</value>
<value letter_id="letter_Y">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">1.000000</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_D">0.000000</value>
<value letter_id="letter_E">0.000000</value>
<value letter_id="letter_F">0.000000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_H">0.000000</value>
<value letter_id="letter_I">0.000000</value>
<value letter_id="letter_K">0.000000</value>
<value letter_id="letter_L">0.000000</value>
<value letter_id="letter_M">0.000000</value>
<value letter_id="letter_N">0.000000</value>
<value letter_id="letter_P">0.000000</value>
<value letter_id="letter_Q">0.000000</value>
<value letter_id="letter_R">0.000000</value>
<value letter_id="letter_S">0.000000</value>
<value letter_id="letter_T">0.000000</value>
<value letter_id="letter_V">0.000000</value>
<value letter_id="letter_W">0.000000</value>
<value letter_id="letter_Y">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.760000</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_D">0.000000</value>
<value letter_id="letter_E">0.000000</value>
<value letter_id="letter_F">0.000000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_H">0.000000</value>
<value letter_id="letter_I">0.000000</value>
<value letter_id="letter_K">0.000000</value>
<value letter_id="letter_L">0.000000</value>
<value letter_id="letter_M">0.000000</value>
<value letter_id="letter_N">0.000000</value>
<value letter_id="letter_P">0.000000</value>
<value letter_id="letter_Q">0.000000</value>
<value letter_id="letter_R">0.000000</value>
<value letter_id="letter_S">0.000000</value>
<value letter_id="letter_T">0.240000</value>
<value letter_id="letter_V">0.000000</value>
<value letter_id="letter_W">0.000000</value>
<value letter_id="letter_Y">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.960000</value>
<value letter_id="letter_C">0.040000</value>
<value letter_id="letter_D">0.000000</value>
<value letter_id="letter_E">0.000000</value>
<value letter_id="letter_F">0.000000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_H">0.000000</value>
<value letter_id="letter_I">0.000000</value>
<value letter_id="letter_K">0.000000</value>
<value letter_id="letter_L">0.000000</value>
<value letter_id="letter_M">0.000000</value>